// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TennisIntelligence.Data;

#nullable disable

namespace TennisIntelligence.Migrations
{
    [DbContext(typeof(TennisDbContext))]
    [Migration("20260802105631_AddWearableImports")]
    partial class AddWearableImports
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TennisIntelligence.Models.DevelopmentGoal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("DevelopmentGoals");
                });

            modelBuilder.Entity("TennisIntelligence.Models.ExternalWorkout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("AverageHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<decimal?>("CaloriesKcal")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("DistanceMeters")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)");

                    b.Property<DateTimeOffset>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("LastImportBatchId")
                        .HasColumnType("integer");

                    b.Property<int?>("MaxHeartRateBpm")
                        .HasColumnType("integer");

                    b.Property<string>("RawPayload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SourceApplication")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset?>("SourceLastModifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceRecordId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("LastImportBatchId");

                    b.HasIndex("StartedAt");

                    b.HasIndex("Source", "SourceRecordId")
                        .IsUnique();

                    b.ToTable("ExternalWorkouts");
                });

            modelBuilder.Entity("TennisIntelligence.Models.GoalCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GoalId")
                        .HasColumnType("integer");

                    b.Property<string>("HowItFelt")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Note")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("SessionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SessionId");

                    b.HasIndex("GoalId", "SessionId")
                        .IsUnique();

                    b.ToTable("GoalCheckIns");
                });

            modelBuilder.Entity("TennisIntelligence.Models.ImportBatch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("ExportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("InsertedRecords")
                        .HasColumnType("integer");

                    b.Property<int>("RejectedRecords")
                        .HasColumnType("integer");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("TotalRecords")
                        .HasColumnType("integer");

                    b.Property<int>("UnchangedRecords")
                        .HasColumnType("integer");

                    b.Property<int>("UpdatedRecords")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ImportedAt");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("TennisIntelligence.Models.InteractionLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Metadata")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PageName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Action", "Timestamp");

                    b.ToTable("InteractionLogs");
                });

            modelBuilder.Entity("TennisIntelligence.Models.Session", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("BodyFeel")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("BreakdownAreas")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("BreakdownReasons")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<int?>("ElbowPain")
                        .HasColumnType("integer");

                    b.Property<string>("EnergyAfter")
                        .HasColumnType("text");

                    b.Property<string>("EnergyBefore")
                        .HasColumnType("text");

                    b.Property<int>("EnergyLevel")
                        .HasColumnType("integer");

                    b.Property<bool?>("FocusAchieved")
                        .HasColumnType("boolean");

                    b.Property<string>("FocusArea")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MatchFormat")
                        .HasColumnType("text");

                    b.Property<string>("MatchResult")
                        .HasColumnType("text");

                    b.Property<string>("MentalState")
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("OpponentLevel")
                        .HasColumnType("text");

                    b.Property<string>("PlayStyle")
                        .HasColumnType("text");

                    b.Property<int?>("SessionRating")
                        .HasColumnType("integer");

                    b.Property<string>("SessionType")
                        .HasColumnType("text");

                    b.Property<int?>("ShoulderTightness")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Sessions");
                });

            modelBuilder.Entity("TennisIntelligence.Models.ExternalWorkout", b =>
                {
                    b.HasOne("TennisIntelligence.Models.ImportBatch", "LastImportBatch")
                        .WithMany()
                        .HasForeignKey("LastImportBatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LastImportBatch");
                });

            modelBuilder.Entity("TennisIntelligence.Models.GoalCheckIn", b =>
                {
                    b.HasOne("TennisIntelligence.Models.DevelopmentGoal", "Goal")
                        .WithMany("CheckIns")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TennisIntelligence.Models.Session", "Session")
                        .WithMany("GoalCheckIns")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TennisIntelligence.Models.DevelopmentGoal", b =>
                {
                    b.Navigation("CheckIns");
                });

            modelBuilder.Entity("TennisIntelligence.Models.Session", b =>
                {
                    b.Navigation("GoalCheckIns");
                });
#pragma warning restore 612, 618
        }
    }
}
